### ISSUE TITLE
[Il2cpp] Honey Come GetPrivateExplicit Extension crash/null object reference

### ISSUE THREAD

**Issue by jalil49** [ManlyMarco/RuntimeUnityEditor#60]
![image](https://github.com/ManlyMarco/RuntimeUnityEditor/assets/63772680/fc1a26c4-395a-4535-8d28-6b44efb95318)
CustomScene/UI/Root/Cvs_CategorySelectionTop/CategoryTop(Clone)/04_Accessories/Index/Background
Issue occurs in siblings of background element

**Comment by jalil49** [comment]
Replicable also on Buttons in UI
![image](https://github.com/ManlyMarco/RuntimeUnityEditor/assets/63772680/216e5daf-0b3e-4fb4-b812-3865c8042ade)

(Child elements are intractable, but  btnCC is not)

**Comment by jalil49** [comment]
Maker:

Unable to open "CustomScene/UI/Root/Cvs_CategoryView" different issue.

Tab just does not seem to stay open and I can really only see the "top" category before it disappears/closes

System.MissingMethodException: Method not found: 'IntPtr Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(UInt32)'.
   at XUnity.Common.Extensions.ObjectExtensions.IsCollected(Il2CppObjectBase that)
   at XUnity.Common.Utilities.ExtensionDataHelper.Cull()
   at XUnity.Common.Utilities.MaintenanceHelper.MaintenanceLoop(Object state)

**Comment by ManlyMarco** [comment]
This should be resolved by now.
