### ISSUE TITLE
[IL2CPP] Memory Access Violation on Startup

### ISSUE THREAD

**Issue by WTFBlaze** [ManlyMarco/RuntimeUnityEditor#82]
# Error
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_gchandle_get_target(IntPtr)
--------------------------------
   at Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase.get_Pointer()
   at Il2CppInterop.Runtime.IL2CPP.Il2CppObjectBaseToPtr(Il2CppInterop.Runtime.InteropTypes.Il2CppObjectBase)
   at UnityEngine.GUILayoutOption..ctor(Type, Il2CppSystem.Object)
   at UnityEngine.GUILayout.MaxWidth(Single)
   at RuntimeUnityEditor.Core.Inspector.Inspector..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type, Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type)
   at System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Linq.Enumerable+<CastIterator>d__63`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Collections.Generic.List`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToList[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at RuntimeUnityEditor.Core.RuntimeUnityEditorCore..ctor(RuntimeUnityEditor.Core.Utils.Abstractions.InitSettings)
   at RuntimeUnityEditor.Bepin6.IL2CPP.RuntimeUnityEditorPluginIL2CPP.Load()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.LoadPlugin(BepInEx.PluginInfo, System.Reflection.Assembly)
   at BepInEx.Bootstrap.BaseChainloader`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].LoadPlugins(System.Collections.Generic.List`1<BepInEx.PluginInfo>, Boolean)
   at BepInEx.Bootstrap.BaseChainloader`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Execute()
   at BepInEx.Unity.IL2CPP.IL2CPPChainloader.OnInvokeMethod(IntPtr, IntPtr, IntPtr, IntPtr)
```

# BepInEx / Game Info
```
[Message: Preloader] BepInEx 6.0.0-be.711 - DDSS
[Message: Preloader] Built from commit f800cbcc43f774d3adb0b1a9c264f0326a5d9f38
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2023.2.6f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
```

**Comment by ManlyMarco** [comment]
Most likely stripped down IMGUI assembly, see https://github.com/ManlyMarco/RuntimeUnityEditor/pull/56#issuecomment-1830875516 and the release notes.

**Comment by ManlyMarco** [comment]
Moving to #97
